spring:
  application:
    name: backend-demo-one
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:5000/o
        registration:
          oidc:
            client-id: internal
            client-secret: internal

# Allowed audience list
oidc:
  audience-list: ccd-admin,ccd-whatever,hmcts
  issuer: http://localhost:8080/openam/oauth2/hmcts

server:
  port: 5080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
